name: Laravel Development

on: ['push', 'pull_request']

jobs:
  laravel-tests:
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: ['ubuntu-20.04', 'ubuntu-18.04']
        php-versions: ['7.4']

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug
        tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Composer Install
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Composer Update
      run: composer update --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate laravel key
      run: php artisan key:generate

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Database Migrate With Seeds
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate:refresh --seed --no-interaction --env=testing

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
